name: golang-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.22.1
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global --add safe.directory /__w/go_final_project/go_final_project

      - name: Set up Go environment
        run: GOOS=linux GOARCH=amd64 go mod tidy

      - name: Build Application
        run: go build -v .

      - name: Run Application
        run: ./go_final_project &

      - name: Run Test 1 TestApp
        run: |
          go test  -run ^TestApp$ ./tests

      - name: Run Test 2 TestDB
        run: |
          go test -run ^TestDB$ ./tests

      - name: Run Test 3 TestNextDate
        run: |
          go test -run ^TestNextDate$ ./tests

      - name: Run Test 4 TestAddTask
        run: |
          go test -run ^TestAddTask$ ./tests

      - name: Run Test 5 TestTasks
        run: |
          go test -run ^TestTasks$ ./tests

      - name: Run Test 6.1 TestTask
        run: |
          go test -run ^TestTask$ ./tests

      - name: Run Test 6.2 TesteditTask
        run: |
          go test -run ^TestEditTask$ ./tests

      - name: Run Test 7.1 TestDone
        run: |
          go test -run ^TestDone$ ./tests

      - name: Run Test 7.2 TestDelTask
        run: |
          go test -run ^TestDelTask$ ./tests

      - name: Vet
        run: |
          go vet ./...

  # deploy:
  #   name: Push Docker image to Docker Hub
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: startsWith(github.ref, 'refs/tags/')
  #   steps:
  #       - name: Checkout
  #         uses: actions/checkout@v4

  #       - name: Set up Docker Buildx
  #         uses: docker/setup-buildx-action@v3

  #       - name: Log in to Docker Hub
  #         uses: docker/login-action@v3
  #         with:
  #           username: ${{ secrets.DOCKER_USERNAME }}
  #           password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

  #       - name: Extract metdata (tags, labels) for Docker
  #         id: meta
  #         uses: docker/metadata-action@v5.5.1
  #         with:
  #           images: ag89201/final-main

  #       - name: Build and push Docker image
  #         uses: docker/build-push-action@v5
  #         with:
  #           context: .
  #           push: true
  #           tags: ${{ steps.meta.outputs.tags }}
  #           labels: ${{ steps.meta.outputs.labels }}